### PR TITLE
Proposal to separate Util class into a Utilities namespace

### PR DESCRIPTION
**Pull request by BioChristou**
I'd like to propose breaking up the `Util` class into separate classes under a `Plivo.Utilities` namespace. This should make it easier to add additional utility functions/classes moving forward.

The change would not be backwards compatible, anyone currently using the `Util` class would have to update their code to use the corresponding Utility class, and add a `using Plivo.Utilities;` declaration

### CODE REVIEW

**Comment by plivo-sdks** [comment]
@BioChristou Thanks for the PR, and it is a good idea to break a huge class into several modular functions/classes so the code is easier to maintain. The initial idea was to have all utils in the `Util` class, but it has grown out of proportion already!

But, I would say this would be a good addition to 4.1.x as I am not convinced the benefit of this addition vs introducing a breaking change. We should probably still keep the `Util` class so it would still be backward-compatible, but the new functionality would be added to `Plivo.Utilities` and may be deprecate the `Util` class later.

**Comment by BioChristou** [comment]
@plivo-sdks thanks for the insight. What do you think of the following idea: I could restore the current `Util` class, route all of its implementations over to the `Plivo.Utilities` versions, and mark the `Util` methods/classes with `[Obsolete]`, including a comment referencing the new location.  This would maintain backwards compatibility until it is a good time to introduce a breaking change.

**Comment by plivo-sdks** [comment]
@BioChristou I think that makes perfect sense. If you already have the code ready for this, feel free to update the PR so we can merge it. Else, we will create an issue for this and start working on this.

**Comment by BioChristou** [comment]
@plivo-sdks I do not have code ready for this presently. If you are able to take on the retroactive shim that would be great.

**Comment by plivo-sdks** [comment]
@BioChristou merging this in.

**Pull request merged**
