### PR TITLE
Updated the RestClient to use a new Uri (for new versions of RestSharp)

### PR DESCRIPTION
**Pull request by rorpage**
I signed up for Plivo last night and read there was a similar issue with a competitor's .NET client, so I thought we could update this one. I'm successfully using RestSharp 105.1 with the Plivo library and this update.

Thanks!
Rob

### CODE REVIEW

**Comment by tsudot** [comment]
@rorpage Thanks for the PR, we'll merge this shortly.

**Comment by tsudot** [comment]
@rorpage Could you add the new version to packages.config ?

**Comment by sdebnath** [comment]
https://github.com/EIrwin/plivo-dotnet/commit/89abe8912635c24a7a06059f9cb2a902bb98df22 looks like a better commit to pull and merge if @EIrwin can pull it into a separate singleton PR. @tsudot any chance we can get this in soon?

**Comment by sdebnath** [comment]
@tsudot any chance this can get merged in?

**Comment by tsudot** [comment]
@sdebnath could you please add the RestSharp version to packages.config?

**Comment by sdebnath** [comment]
@tsudot I think it might be better to add a specific dependency on the restsharp 105 than to bundle it with this package. If its okay with you guys, I will send up a PR by end of day.

**Comment by sdebnath** [comment]
@tsudot this can be closed now since #22 went in

**Pull request closed without merging**
