### PR TITLE
Cleaned up Library

### PR DESCRIPTION
**Pull request by EIrwin**
This is a WAYYYYY cleaner implementation of plivo-dotnet that conforms more closely to .NET standards and coding practices. You want better adoption from the C# and .NET users, then I would recommend making these changes.

### CODE REVIEW

**Comment by sandeepraju** [comment]
@EIrwin thanks for your pull request. We'll review this shortly and merge it to master.

**Comment by tsudot** [comment]
@EIrwin could you add some examples in the README on how to use the helper?

**Comment by EIrwin** [comment]
@tsudot Which helper are you referring to? You just want me to add some examples of using the updated library?

**Comment by tsudot** [comment]
Yes, just the examples on how to use the library.

**Comment by EIrwin** [comment]
@tsudot do you have suggestions on what you want examples to be on?

**Comment by tsudot** [comment]
Basic things like making a call, sending an SMS, generating XML (Dial, Speak, GetDigits)

**Comment by EIrwin** [comment]
@tsudot I will work on some examples and test them. I will let you know when they are ready.

**Comment by Ramya-Raghu** [comment]
Included in 2.0.0 release

**Pull request closed without merging**
